# Generated by Django 4.2.7 on 2023-11-29 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('site', models.CharField(max_length=50)),
                ('hemis_site', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
